#!/usr/bin/python3
"""Defines unittests for models/place.py

Unittest classes:
        TestPlace_instantiation
        TestPlace__str__
        TestPlace_save
        TestPlace_to_dict
"""
import unittest
from models.place import Place
from time import sleep
from datetime import datetime


class TestPlace_instantiation(unittest.TestCase):
    """Unittests for the instantiation of the Place class."""

    def test_no_args_instantiation(self):
        self.assertEqual(Place, type(Place()))

    def test_id_exists(self):
        self.assertTrue(Place().id)

    def test_id_is_public_str(self):
        self.assertEqual(str, type(Place().id))

    def test_id_is_unique(self):
        self.assertNotEqual(Place().id, Place().id)

    def test_created_at_exists(self):
        self.assertTrue(Place().created_at)

    def test_created_at_is_public_datetime(self):
        self.assertTrue(type(Place().created_at), datetime)

    def test_two_models_different_created_at(self):
        model1 = Place()
        sleep(0.05)
        model2 = Place()
        self.assertLess(model1.created_at, model2.created_at)

    def test_created_at_does_not_change(self):
        model = Place()
        sleep(0.05)
        created_at = model.created_at
        model.save()
        self.assertEqual(model.created_at, created_at)

    def test_updated_at_exists(self):
        self.assertTrue(Place().updated_at)

    def test_updated_at_is_public_datetime(self):
        self.assertTrue(type(Place().updated_at), datetime)

    def test_updated_at_updates(self):
        model = Place()
        updated_at = model.updated_at
        sleep(0.05)
        model.save()
        self.assertNotEqual(updated_at, model.updated_at)

    def test_city_id_is_public_str(self):
        self.assertEqual(str, type(Place().city_id))

    def test_user_id_is_public_str(self):
        self.assertEqual(str, type(Place().user_id))

    def test_name_is_public_str(self):
        self.assertEqual(str, type(Place().name))

    def test_description_is_public_str(self):
        self.assertEqual(str, type(Place().name))

    def test_number_rooms_is_public_str(self):
        self.assertEqual(int, type(Place().number_rooms))

    def test_number_bathrooms_is_public_str(self):
        self.assertEqual(int, type(Place().number_bathrooms))

    def test_max_guest_is_public_str(self):
        self.assertEqual(int, type(Place().max_guest))

    def test_price_by_night_is_public_str(self):
        self.assertEqual(int, type(Place().price_by_night))

    def test_latitude_is_public_str(self):
        self.assertEqual(float, type(Place().latitude))

    def test_longitude_is_public_str(self):
        self.assertEqual(float, type(Place().longitude))

    def test_amenity_ids_is_public_str(self):
        self.assertEqual(list, type(Place().amenity_ids))


class TestPlace__str__(unittest.TestCase):
    """Unittest for testing __str__ method of the Place class."""

    def test_str_exists(self):
        self.assertIn("__str__", dir(Place()))

    def test_str_type(self):
        model = Place()
        self.assertEqual(type(model.__str__()), str)

    def test_arg_in_str(self):
        model = Place()
        with self.assertRaises(TypeError):
            model.__str__(None)

    def test_str_representation(self):
        dt = datetime.utcnow()
        dt_repr = repr(dt)
        model = Place()
        model.id = "12345"
        model.created_at = model.updated_at = dt
        modelstr = model.__str__()
        self.assertIn("[Place] (12345)", modelstr)
        self.assertIn("'id': '12345'", modelstr)
        self.assertIn("'created_at': " + dt_repr, modelstr)
        self.assertIn("'updated_at': " + dt_repr, modelstr)


class TestPlace_save(unittest.TestCase):
    """Unittests for testing save method of the Place class."""

    def test_save_exists(self):
        self.assertIn("save", dir(Place()))

    def test_save_updates_updated_at_attr(self):
        model = Place()
        updated_at = model.updated_at
        sleep(0.05)
        model.save()
        self.assertNotEqual(updated_at, model.updated_at)

    def test_save_calls_storage(self):
        model = Place()
        model.save()
        with open("file.json", "r") as f:
            key = "Place." + model.id
            self.assertIn(key, f.read())

    def test_save_with_arg(self):
        model = Place()
        with self.assertRaises(TypeError):
            model.save(datetime.utcnow())


class TestPlace_to_dict(unittest.TestCase):
    """Unittest for testing to_dict method of the Place class."""

    def test_to_dict_exits(self):
        self.assertTrue(Place().to_dict())

    def test_to_dict_type(self):
        model = Place()
        self.assertTrue(type(model.to_dict()), dict)

    def test_to_dict_contains_correct_keys(self):
        model = Place()
        model.place_id = "1234-1234-1234"
        model.user_id = "4321-4321-4321"
        model.text = "I love this place"
        self.assertIn("id", model.to_dict())
        self.assertIn("created_at", model.to_dict())
        self.assertIn("updated_at", model.to_dict())
        self.assertIn("place_id", model.to_dict())
        self.assertIn("user_id", model.to_dict())
        self.assertIn("text", model.to_dict())

    def test_to_dict_contains_added_keys(self):
        model = Place()
        model.name = "Ubuntu"
        model.version = 22.04
        self.assertIn("name", model.to_dict())
        self.assertIn("version", model.to_dict())


if __name__ == "__main__":
    unittest.main()  #!/usr/bin/python3
"""Defines unittests for models/Place.py

Unittest classes:
        TestPlace_instantiation
        TestPlace__str__
        TestPlace_save
        TestPlace_to_dict
"""
import unittest
from models.Place import Place
from time import sleep
from datetime import datetime


class TestPlace_instantiation(unittest.TestCase):
    """Unittests for the instantiation of the Place class."""

    def test_no_args_instantiation(self):
        self.assertEqual(Place, type(Place()))

    def test_id_exists(self):
        self.assertTrue(Place().id)

    def test_id_is_public_str(self):
        self.assertEqual(str, type(Place().id))

    def test_id_is_unique(self):
        self.assertNotEqual(Place().id, Place().id)

    def test_created_at_exists(self):
        self.assertTrue(Place().created_at)

    def test_created_at_is_public_datetime(self):
        self.assertTrue(type(Place().created_at), datetime)

    def test_two_models_different_created_at(self):
        model1 = Place()
        sleep(0.05)
        model2 = Place()
        self.assertLess(model1.created_at, model2.created_at)

    def test_created_at_does_not_change(self):
        model = Place()
        sleep(0.05)
        created_at = model.created_at
        model.save()
        self.assertEqual(model.created_at, created_at)

    def test_updated_at_exists(self):
        self.assertTrue(Place().updated_at)

    def test_updated_at_is_public_datetime(self):
        self.assertTrue(type(Place().updated_at), datetime)

    def test_updated_at_updates(self):
        model = Place()
        updated_at = model.updated_at
        sleep(0.05)
        model.save()
        self.assertNotEqual(updated_at, model.updated_at)

    def test_place_id_is_public_str(self):
        self.assertEqual(str, type(Place().place_id))

    def test_user_id_is_public_str(self):
        self.assertEqual(str, type(Place().user_id))

    def test_text_is_public_str(self):
        self.assertEqual(str, type(Place().text))


class TestPlace__str__(unittest.TestCase):
    """Unittest for testing __str__ method of the Place class."""

    def test_str_exists(self):
        self.assertIn("__str__", dir(Place()))

    def test_str_type(self):
        model = Place()
        self.assertEqual(type(model.__str__()), str)

    def test_arg_in_str(self):
        model = Place()
        with self.assertRaises(TypeError):
            model.__str__(None)

    def test_str_representation(self):
        dt = datetime.utcnow()
        dt_repr = repr(dt)
        model = Place()
        model.created_at = model.updated_at = dt
        modelstr = model.__str__()
        self.assertIn("[Place] (12345)", modelstr)
        self.assertIn("'id': '12345'", modelstr)
        self.assertIn("'created_at': " + dt_repr, modelstr)
        self.assertIn("'updated_at': " + dt_repr, modelstr)


class TestPlace_save(unittest.TestCase):
    """Unittests for testing save method of the Place class."""

    def test_save_exists(self):
        self.assertIn("save", dir(Place()))

    def test_save_updates_updated_at_attr(self):
        model = Place()
        updated_at = model.updated_at
        sleep(0.05)
        model.save()
        self.assertNotEqual(updated_at, model.updated_at)

    def test_save_calls_storage(self):
        model = Place()
        model.save()
        with open("file.json", "r") as f:
            key = "Place." + model.id
            self.assertIn(key, f.read())

    def test_save_with_arg(self):
        model = Place()
        with self.assertRaises(TypeError):
            model.save(datetime.utcnow())


class TestPlace_to_dict(unittest.TestCase):
    """Unittest for testing to_dict method of the Place class."""

    def test_to_dict_exits(self):
        self.assertTrue(Place().to_dict())

    def test_to_dict_type(self):
        model = Place()
        self.assertTrue(type(model.to_dict()), dict)

    def test_to_dict_contains_correct_keys(self):
        model = Place()
        model.name = "Ikeja"
        model.description = ""
        model.number_rooms = 4
        model.number_bathrooms = 3
        model.max_guest = 3
        model.price_by_night = 500
        model.latitude = 0.0
        model.longitude = 0.0
        model.amenity_ids = []
        self.assertIn("id", model.to_dict())
        self.assertIn("created_at", model.to_dict())
        self.assertIn("updated_at", model.to_dict())
        self.assertIn("place_id", model.to_dict())
        self.assertIn("city_id", model.to_dict())
        self.assertIn("user", model.to_dict())

    def test_to_dict_contains_added_keys(self):
        model = Place()
        model.name = "Ubuntu"
        model.version = 22.04
        self.assertIn("name", model.to_dict())
        self.assertIn("version", model.to_dict())


if __name__ == "__main__":
    unittest.main()
